### ISSUE TITLE
Enable Discussions?

### ISSUE THREAD

**Issue by hylkevds** [INSPIRE-MIF/gp-ogc-sensorthings-api#2]
GitHub offers a Discussions forum, besides this Issues List. Discussions are more open-ended, whereas Issues (like this one) are resolved and then closed. Closed Issues disappear from the List, unless once specifically searches for closed Issues.

Could the Discussions be enabled here? It's under Settings (Features) -> Discussions

**Comment by sgrellet** [comment]
+1 on this that would help coordinate (and pass the word) about activities around SensorThings API.
One example worth sharing ST API capability in QGIS Core : https://github.com/qgis/QGIS-Enhancement-Proposals/issues/257

**Comment by MarcoMinghini** [comment]
Dear @hylkevds and @sgrellet, Discussions enabled (with the standard options, please let us know if you need any customisation).

**Comment by hylkevds** [comment]
Super, thank you very much!
